"""new description field in recipes

Revision ID: 0c4cb1e059e8
Revises: 
Create Date: 2023-09-17 20:10:13.370491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4cb1e059e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=3000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=True)

    # ### end Alembic commands ###
